"""Golden render tests for the D4 report builders (design 6.4.5, Phase 3).

The documents below are constructed through :func:`build_report` over typed
Phase 2 inputs.  Golden expectations are hand-authored constants and fixture
files produced once by helper scripts *outside* the code under test — they
are never generated by the renderers inside a test run.  The pinned
``ReviewSet`` shape is provided by ``reporting.review`` when present and by
the structural fallback in ``reporting.model`` otherwise; these tests only
use the pinned fields.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from mtsql_typecheck.contracts.case import ContractError
from mtsql_typecheck.contracts.codec import canonical_json, parse_strict_json
from mtsql_typecheck.contracts.delivery import (
    AssessmentDimension,
    DimensionResult,
    EvidenceFile,
    FileRole,
    FindingOccurrence,
    FindingReview,
    NativeKind,
    ReviewDecision,
    SemanticStatus,
    StructuralStatus,
    SyntheticKind,
    ExecutionSafetyStatus,
    ProvenanceStatus,
)
from mtsql_typecheck.evidence.assessment import (
    AttemptSemanticResult,
    SelectionProof,
    SourceAssessment,
)
from mtsql_typecheck.evidence.manifest import Problem
from mtsql_typecheck.reporting.build import bound_diff_summary, build_report
from mtsql_typecheck.reporting.markdown import render_markdown
from mtsql_typecheck.reporting.html import render_html
from mtsql_typecheck.reporting.model import (
    CaseDetailInput,
    CoverageEntry,
    CoverageSummary,
    ExecutionCounts,
    FindingsSummary,
    GenerationCounts,
    LimitExceeded,
    ReportDocument,
    UnsafeLinkError,
    decode_report_document,
)

FIXTURES = Path(__file__).parent / "fixtures"

# --------------------------------------------------------------------------
# Frozen fixture constants (chosen literals, not derived)
# --------------------------------------------------------------------------

SOURCE_ID = "s-" + "ab" * 32
OTHER_SOURCE_ID = "s-" + "ef" * 32
DELIVERY_ID = "cd" * 32
COMMIT = "a1b2c3d4e5" * 4
GENERATED_AT = "2026-09-06T12:00:00Z"
CASE_A = "aa" * 32
CASE_B = "bb" * 32
CASE_C = "cc" * 32
HASH_1 = "11" * 32
HASH_2 = "22" * 32
FINGERPRINT = "33" * 32
ATTEMPT_1 = "attempt-1"
ATTEMPT_2 = "attempt-2"


# --------------------------------------------------------------------------
# Typed input builders
# --------------------------------------------------------------------------


def _dim(
    dimension: AssessmentDimension,
    status,
    *,
    applicable: bool = True,
    checked: int = 1,
    unchecked: int = 0,
    reason_codes: tuple[str, ...] = (),
    detail: str | None = None,
) -> DimensionResult:
    return DimensionResult(
        dimension=dimension,
        applicable=applicable,
        status=status,
        reason_codes=reason_codes,
        checked_objects=checked,
        unchecked_objects=unchecked,
        detail=detail,
    )


def _dims(
    structural=StructuralStatus.COMPLETE,
    semantic=SemanticStatus.RECOMPUTED,
    provenance=ProvenanceStatus.CORROBORATED,
    safety=ExecutionSafetyStatus.CONFIRMED,
    *,
    structural_kwargs=None,
    semantic_kwargs=None,
    provenance_kwargs=None,
    safety_kwargs=None,
):
    return (
        _dim(AssessmentDimension.STRUCTURAL, structural, **(structural_kwargs or {})),
        _dim(AssessmentDimension.SEMANTIC, semantic, **(semantic_kwargs or {})),
        _dim(AssessmentDimension.PROVENANCE, provenance, **(provenance_kwargs or {})),
        _dim(AssessmentDimension.EXECUTION_SAFETY, safety, **(safety_kwargs or {})),
    )


def _assessment(dims, *, native_kind=NativeKind.GENERATION, selection=None, attempts=()):
    structural, semantic, provenance, safety = dims
    return SourceAssessment(
        source_id=SOURCE_ID,
        native_kind=native_kind,
        structural=structural,
        semantic=semantic,
        provenance=provenance,
        execution_safety=safety,
        attempts=tuple(attempts),
        selection=selection,
        reason_codes=(),
    )


def _empty_reviews():
    from mtsql_typecheck.reporting.model import ReviewSet

    return ReviewSet(accepted=(), duplicates_ignored=(), historical=(), conflicts=(), has_conflict=False)


def _base_files():
    return (
        EvidenceFile(
            path="assessment.json",
            role=FileRole.ASSESSMENT,
            size_bytes=512,
            sha256=HASH_1,
        ),
        EvidenceFile(
            path=f"raw/{SOURCE_ID}/generation-manifest.json",
            role=FileRole.RAW_NATIVE,
            size_bytes=4096,
            sha256=HASH_2,
            source_id=SOURCE_ID,
        ),
    )


def _zero_findings() -> FindingsSummary:
    return FindingsSummary(
        real_candidates=0,
        synthetic_candidates=0,
        unknown_synthetic_candidates=0,
        conflicts=0,
        unique_case_ids=0,
        distinct_signatures=0,
        distinct_fingerprints=0,
        reviewed_confirmed=0,
    )


def _occurrence(case_id: str, attempt_id: str, status: SemanticStatus, synthetic=SyntheticKind.REAL):
    recomputed = HASH_1 if status is not SemanticStatus.NOT_RECOMPUTED else None
    return FindingOccurrence(
        source_id=SOURCE_ID,
        attempt_id=attempt_id,
        case_id=case_id,
        recompute_status=status,
        comparison_hash=HASH_2,
        original_exact_signature=HASH_1,
        fingerprint=FINGERPRINT,
        recomputed_comparison_hash=recomputed,
        synthetic=synthetic,
    )


def _build(assessment, **kwargs):
    defaults = dict(
        tool_name="mtsql-typecheck",
        writer_version="4.0.0",
        delivery_id=DELIVERY_ID,
        synthetic=SyntheticKind.REAL,
        findings=_zero_findings(),
        reviews=_empty_reviews(),
        files=_base_files(),
        reproduction_notes=("独立复现请使用 export 生成的 SQL 包",),
        generated_at=GENERATED_AT,
    )
    defaults.update(kwargs)
    return build_report(assessment=assessment, **defaults)


# --------------------------------------------------------------------------
# The seven golden documents
# --------------------------------------------------------------------------


def doc_complete() -> ReportDocument:
    """Smallest complete document: all four dimensions finished (6.4.5 item 1)."""
    assessment = _assessment(_dims())
    return _build(assessment)


def doc_partial() -> ReportDocument:
    """Partial document: unchecked semantic/provenance objects, counts present."""
    assessment = _assessment(
        _dims(
            semantic=SemanticStatus.NOT_RECOMPUTED,
            provenance=ProvenanceStatus.UNVERIFIED,
            semantic_kwargs=dict(checked=1, unchecked=2, reason_codes=("document_missing",)),
            provenance_kwargs=dict(checked=0, unchecked=2),
        ),
        native_kind=NativeKind.RUN,
        attempts=(
            AttemptSemanticResult(
                source_id=SOURCE_ID,
                attempt_id=ATTEMPT_1,
                case_id=CASE_A,
                original_comparison_hash=HASH_2,
                static_check_status="PASS",
                recompute=SemanticStatus.RECOMPUTED,
                recomputed_comparison_hash=HASH_1,
                exact_signature=HASH_1,
                fingerprint=FINGERPRINT,
                synthetic=SyntheticKind.REAL,
                reason_codes=(),
                limit_reasons=(),
            ),
        ),
    )
    return _build(
        assessment,
        occurrences=(_occurrence(CASE_A, ATTEMPT_1, SemanticStatus.RECOMPUTED),),
        findings=FindingsSummary(
            real_candidates=1,
            synthetic_candidates=0,
            unknown_synthetic_candidates=0,
            conflicts=0,
            unique_case_ids=1,
            distinct_signatures=1,
            distinct_fingerprints=1,
            reviewed_confirmed=0,
        ),
        generation_counts=GenerationCounts(
            requested_ordinals=12,
            attempted_candidates=10,
            emitted_occurrences=9,
            unique_cases=8,
            rejected_ordinals=1,
            interrupted_ordinals=1,
            not_attempted=0,
            receipt_recheck="CONSERVED",
            denominator_known=True,
        ),
        execution_counts=ExecutionCounts(
            requested_attempts=9,
            completed_both_selects=7,
            match_candidates=2,
            not_applicable=1,
            undecidable=1,
            preflight_failures=0,
            undispatched=1,
        ),
        coverage=CoverageSummary(
            entries=(
                CoverageEntry(
                    rule_id="int_overflow",
                    rule_version=2,
                    type_pair="int8~int8",
                    template="basic",
                    index_variant="none",
                    comparable_unique_cases=3,
                    denominator=12,
                ),
            ),
            denominator_known=True,
            unknown_reason=None,
            identity_only_cases=1,
            empty_result_cases=2,
        ),
        original_run_status="COMPLETED",
    )


def doc_conflict() -> ReportDocument:
    """Semantic conflict plus mutually exclusive human reviews (6.4.5)."""
    from mtsql_typecheck.reporting.model import ReviewConflict, ReviewSet

    assessment = _assessment(
        _dims(
            semantic=SemanticStatus.CONFLICT,
            semantic_kwargs=dict(checked=2, reason_codes=("recompute_mismatch",)),
        ),
        native_kind=NativeKind.TRACE,
        attempts=(
            AttemptSemanticResult(
                source_id=SOURCE_ID,
                attempt_id=ATTEMPT_1,
                case_id=CASE_A,
                original_comparison_hash=HASH_2,
                static_check_status="PASS",
                recompute=SemanticStatus.CONFLICT,
                recomputed_comparison_hash=HASH_1,
                exact_signature=HASH_1,
                fingerprint=FINGERPRINT,
                synthetic=SyntheticKind.REAL,
                reason_codes=("recompute_mismatch",),
                limit_reasons=(),
            ),
        ),
    )
    occurrence = _occurrence(CASE_A, ATTEMPT_1, SemanticStatus.CONFLICT)
    review_1 = FindingReview(
        review_id="rev-1",
        reviewer="alice",
        reviewed_at="2026-09-06T13:00:00Z",
        evidence_digest=DELIVERY_ID,
        occurrence_ids=(occurrence.occurrence_id,),
        decision=ReviewDecision.CONFIRMED_DB_BUG,
        reason="复算差异稳定，确认为数据库整数溢出行为",
        issue_url="https://example.com/issue/1",
    )
    review_2 = FindingReview(
        review_id="rev-2",
        reviewer="bob",
        reviewed_at="2026-09-06T14:00:00Z",
        evidence_digest=DELIVERY_ID,
        occurrence_ids=(occurrence.occurrence_id,),
        decision=ReviewDecision.EXPECTED_BEHAVIOR,
        reason="该行为符合 SQL 标准的溢出处理",
    )
    reviews = ReviewSet(
        accepted=(review_1, review_2),
        duplicates_ignored=(),
        historical=(),
        conflicts=(
            ReviewConflict(
                occurrence_ids=(occurrence.occurrence_id,),
                review_ids=("rev-1", "rev-2"),
                detail="CONFIRMED_DB_BUG 与 EXPECTED_BEHAVIOR 互斥",
            ),
        ),
        has_conflict=True,
    )
    return _build(
        assessment,
        occurrences=(occurrence,),
        case_details=(
            CaseDetailInput(
                occurrence_id=occurrence.occurrence_id,
                case_id=CASE_A,
                rule_id="int_overflow",
                rule_version=2,
                type_pair="int8~int8",
                select_text="SELECT a | b FROM t",
                diff_summary="A: 2 行\nB: 3 行 | 差异见上",
                original_ref="raw/x/attempts/attempt-1/comparison.json",
                best_ref="raw/x/attempts/attempt-1/reduced-child.json",
                round_outcomes=("round1:FULL_VERIFIED", "round2:SEMANTIC_MISMATCH"),
                review_ids=("rev-1", "rev-2"),
            ),
        ),
        findings=FindingsSummary(
            real_candidates=1,
            synthetic_candidates=0,
            unknown_synthetic_candidates=0,
            conflicts=1,
            unique_case_ids=1,
            distinct_signatures=1,
            distinct_fingerprints=1,
            reviewed_confirmed=0,
        ),
        reviews=reviews,
        problems=(
            Problem(code="hash_mismatch", path="raw/x/extra.json", detail="sha256 不匹配"),
        ),
        original_run_status="PARTIAL",
    )


def doc_legacy() -> ReportDocument:
    """Legacy trace: NOT_RECOMPUTED with a LEGACY selection proof."""
    assessment = _assessment(
        _dims(
            semantic=SemanticStatus.NOT_RECOMPUTED,
            semantic_kwargs=dict(checked=0, unchecked=3, reason_codes=("legacy_trace",)),
        ),
        native_kind=NativeKind.TRACE,
        selection=SelectionProof(
            best_payload_ref=None,
            best_case_id=None,
            chain_verified=False,
            chain_status="LEGACY",
            constraints=("legacy_trace_no_best_export",),
        ),
    )
    return _build(
        assessment,
        known_limitations=("legacy_trace_no_best_export", "producer_version_unknown"),
        original_run_status="FINISHED",
    )


def doc_unknown_safety() -> ReportDocument:
    """Execution safety UNKNOWN: queries recorded without terminal receipts."""
    assessment = _assessment(
        _dims(
            safety=ExecutionSafetyStatus.UNKNOWN,
            safety_kwargs=dict(checked=2, unchecked=0, reason_codes=("queries_without_terminal",)),
        ),
        native_kind=NativeKind.RUN,
        attempts=(
            AttemptSemanticResult(
                source_id=SOURCE_ID,
                attempt_id=ATTEMPT_2,
                case_id=CASE_B,
                original_comparison_hash=HASH_2,
                static_check_status="PASS",
                recompute=SemanticStatus.RECOMPUTED,
                recomputed_comparison_hash=HASH_1,
                exact_signature=HASH_1,
                fingerprint=FINGERPRINT,
                synthetic=SyntheticKind.REAL,
                reason_codes=(),
                limit_reasons=(),
            ),
        ),
    )
    return _build(
        assessment,
        occurrences=(_occurrence(CASE_B, ATTEMPT_2, SemanticStatus.RECOMPUTED),),
        findings=FindingsSummary(
            real_candidates=1,
            synthetic_candidates=0,
            unknown_synthetic_candidates=0,
            conflicts=0,
            unique_case_ids=1,
            distinct_signatures=1,
            distinct_fingerprints=1,
            reviewed_confirmed=0,
        ),
    )


def doc_synthetic_zero() -> ReportDocument:
    """Synthetic source, zero comparable cases, coverage denominator unknown."""
    assessment = _assessment(
        _dims(
            semantic=SemanticStatus.NOT_RECOMPUTED,
            provenance=ProvenanceStatus.UNVERIFIED,
            safety=ExecutionSafetyStatus.NOT_APPLICABLE,
            semantic_kwargs=dict(applicable=False, checked=0, unchecked=0),
            provenance_kwargs=dict(applicable=False, checked=0, unchecked=0),
            safety_kwargs=dict(applicable=False, checked=0, unchecked=0),
        ),
    )
    return _build(
        assessment,
        synthetic=SyntheticKind.SYNTHETIC,
        coverage=CoverageSummary(
            entries=(),
            denominator_known=False,
            unknown_reason="no_profile",
            identity_only_cases=1,
            empty_result_cases=2,
        ),
    )


def doc_longtext() -> ReportDocument:
    """Long SQL, CJK text, big integers and special file names (Phase 3)."""
    assessment = _assessment(
        _dims(),
        native_kind=NativeKind.ATTEMPT,
        attempts=(
            AttemptSemanticResult(
                source_id=SOURCE_ID,
                attempt_id=ATTEMPT_1,
                case_id=CASE_C,
                original_comparison_hash=HASH_2,
                static_check_status="PASS",
                recompute=SemanticStatus.RECOMPUTED,
                recomputed_comparison_hash=HASH_1,
                exact_signature=HASH_1,
                fingerprint=FINGERPRINT,
                synthetic=SyntheticKind.REAL,
                reason_codes=(),
                limit_reasons=(),
            ),
        ),
    )
    long_sql = "SELECT " + ", ".join(f"col{i} AS 中文列{i}" for i in range(40))
    long_diff = "\n".join(f"行 {i}: 值差异很大 —— 甲乙丙丁戊己庚辛壬癸 {i}" for i in range(150))
    occurrence = _occurrence(CASE_C, ATTEMPT_1, SemanticStatus.RECOMPUTED)
    files = _base_files() + (
        EvidenceFile(
            path=f"raw/{SOURCE_ID}/cases/中文 文件名+.json",
            role=FileRole.RAW_NATIVE,
            size_bytes=10**15,
            sha256=HASH_1,
            source_id=SOURCE_ID,
        ),
    )
    return _build(
        assessment,
        occurrences=(occurrence,),
        case_details=(
            CaseDetailInput(
                occurrence_id=occurrence.occurrence_id,
                case_id=CASE_C,
                rule_id="int_overflow",
                rule_version=2,
                type_pair="int8~int8",
                select_text=long_sql,
                diff_summary=long_diff,
            ),
        ),
        files=files,
        findings=FindingsSummary(
            real_candidates=1,
            synthetic_candidates=0,
            unknown_synthetic_candidates=0,
            conflicts=0,
            unique_case_ids=1,
            distinct_signatures=1,
            distinct_fingerprints=1,
            reviewed_confirmed=0,
        ),
    )


def doc_hostile() -> ReportDocument:
    """Injection attempts: HTML, pipes, backticks, newlines in dynamic text."""
    assessment = _assessment(
        _dims(semantic=SemanticStatus.CONFLICT, semantic_kwargs=dict(checked=1)),
        native_kind=NativeKind.RUN,
        attempts=(
            AttemptSemanticResult(
                source_id=SOURCE_ID,
                attempt_id=ATTEMPT_1,
                case_id=CASE_A,
                original_comparison_hash=HASH_2,
                static_check_status="PASS",
                recompute=SemanticStatus.CONFLICT,
                recomputed_comparison_hash=HASH_1,
                exact_signature=HASH_1,
                fingerprint=FINGERPRINT,
                synthetic=SyntheticKind.REAL,
                reason_codes=(),
                limit_reasons=(),
            ),
        ),
    )
    occurrence = _occurrence(CASE_A, ATTEMPT_1, SemanticStatus.CONFLICT)
    return _build(
        assessment,
        occurrences=(occurrence,),
        case_details=(
            CaseDetailInput(
                occurrence_id=occurrence.occurrence_id,
                case_id=CASE_A,
                rule_id="r`ule|with\nnewline",
                rule_version=2,
                type_pair="int8~int8",
                select_text=(
                    "SELECT a | b FROM t -- <script>alert(1)</script>\n"
                    "`x` && <img src=x onerror=alert(2)>"
                ),
                diff_summary="A: <b>1</b> | B: 2\n`backtick` | pipe",
                original_ref="raw/x/attempts/attempt-1/comparison.json",
                round_outcomes=("round1:<script>",),
            ),
        ),
        findings=FindingsSummary(
            real_candidates=1,
            synthetic_candidates=0,
            unknown_synthetic_candidates=0,
            conflicts=1,
            unique_case_ids=1,
            distinct_signatures=1,
            distinct_fingerprints=1,
            reviewed_confirmed=0,
        ),
    )


ALL_DOCS = (
    doc_complete,
    doc_partial,
    doc_conflict,
    doc_legacy,
    doc_unknown_safety,
    doc_synthetic_zero,
    doc_longtext,
    doc_hostile,
)


# --------------------------------------------------------------------------
# Hand-authored golden constants (produced once outside the code under test)
# --------------------------------------------------------------------------

_MD_HEADER_FRAGMENT = """## 版本与来源

| 字段 | 值 |
| --- | --- |
| 工具 | mtsql-typecheck |
| 报告写入器版本 | 4.0.0 |
| 原生格式 | generation |
| 真实/合成 | REAL |
| 原执行状态 | （未记录） |
| 结构审计 | COMPLETE（适用；已查 1，未查 0） |
| 语义审计 | RECOMPUTED（适用；已查 1，未查 0） |
| 来源佐证 | CORROBORATED（适用；已查 1，未查 0） |
| 执行安全 | CONFIRMED（适用；已查 1，未查 0） |"""

_MD_COUNTS_FRAGMENT = "## 计数与覆盖\n\n（无计数数据）"

_MD_FINDINGS_FRAGMENT = "### 候选明细（按风险与稳定 ID 排序）\n\n（无候选）"

_MD_REVIEW_EMPTY_FRAGMENT = "## 人工 Review\n\n（无）"

_MD_NOTE_FRAGMENT = "### 复现说明\n\n1. 独立复现请使用 export 生成的 SQL 包"

_MD_CONFLICT_WARNING_FRAGMENT = (
    "**警告：存在互斥的人工 review 冲突；以下全部意见并列保留，"
    "原始观察未被修改。**"
)

_MD_DISCLAIMER_FRAGMENT = "本报告是证据展示：报告生成不等于测试通过"

_MD_SECTION_ORDER = (
    "## 版本与来源",
    "## 计数与覆盖",
    "## 候选与异常",
    "## Case 明细",
    "## 人工 Review",
    "## 文件清单与复现",
)

_HTML_HEADLINE_FRAGMENT = (
    '<h1>TypeCheck 证据报告 '
    '<span class="badge ok">四维审计完成（非正确性证明）</span></h1>'
)

_HTML_VIEWPORT_FRAGMENT = (
    '<meta name="viewport" content="width=device-width, initial-scale=1">'
)

_HTML_PARTIAL_HEADLINE_FRAGMENT = '<span class="badge warn">部分证据 — 非完整通过</span>'

_HTML_CONFLICT_HEADLINE_FRAGMENT = '<span class="badge bad">'

_HTML_SECTION_HEADS = (
    "<h2>版本与来源</h2>",
    "<h2>计数与覆盖</h2>",
    "<h2>候选与异常</h2>",
    "<h2>Case 明细</h2>",
    "<h2>人工 Review</h2>",
    "<h2>文件清单与复现</h2>",
)

# Hand-authored header object for the smallest complete document; must equal
# the golden fixture's "header" member byte-for-byte in value.
_COMPLETE_HEADER_LITERAL = {
    "tool_name": "mtsql-typecheck",
    "writer_version": "4.0.0",
    "native_kind": "generation",
    "synthetic": "REAL",
    "original_run_status": None,
    "structural": {
        "dimension": "structural",
        "applicable": True,
        "status": "COMPLETE",
        "reason_codes": [],
        "checked_objects": 1,
        "unchecked_objects": 0,
        "detail": None,
    },
    "semantic": {
        "dimension": "semantic",
        "applicable": True,
        "status": "RECOMPUTED",
        "reason_codes": [],
        "checked_objects": 1,
        "unchecked_objects": 0,
        "detail": None,
    },
    "provenance": {
        "dimension": "provenance",
        "applicable": True,
        "status": "CORROBORATED",
        "reason_codes": [],
        "checked_objects": 1,
        "unchecked_objects": 0,
        "detail": None,
    },
    "execution_safety": {
        "dimension": "execution_safety",
        "applicable": True,
        "status": "CONFIRMED",
        "reason_codes": [],
        "checked_objects": 1,
        "unchecked_objects": 0,
        "detail": None,
    },
    "producer": None,
    "source_commit": None,
    "source_id": SOURCE_ID,
    "delivery_id": DELIVERY_ID,
    "generated_at": GENERATED_AT,
    "known_limitations": [],
}


# --------------------------------------------------------------------------
# Golden JSON fixtures
# --------------------------------------------------------------------------


def test_golden_complete_json_bytes():
    doc = doc_complete()
    golden = (FIXTURES / "report_complete.json").read_bytes()
    assert canonical_json(doc.to_obj()) == golden
    obj = json.loads(golden)
    assert obj["schema_version"] == 1
    assert obj["header"] == _COMPLETE_HEADER_LITERAL
    assert obj["reviews"] == {
        "accepted": [],
        "duplicates_ignored": [],
        "historical": [],
        "conflicts": [],
        "has_conflict": False,
    }


def test_golden_conflict_json_bytes():
    doc = doc_conflict()
    golden = (FIXTURES / "report_conflict.json").read_bytes()
    assert canonical_json(doc.to_obj()) == golden
    obj = json.loads(golden)
    assert obj["findings"]["summary"]["conflicts"] == 1
    assert obj["reviews"]["has_conflict"] is True
    assert len(obj["reviews"]["accepted"]) == 2
    assert obj["reviews"]["conflicts"][0]["review_ids"] == ["rev-1", "rev-2"]


# --------------------------------------------------------------------------
# Golden Markdown / HTML fragments
# --------------------------------------------------------------------------


def test_markdown_golden_fragments():
    md = render_markdown(doc_complete())
    assert _MD_HEADER_FRAGMENT in md
    assert _MD_COUNTS_FRAGMENT in md
    assert _MD_FINDINGS_FRAGMENT in md
    assert _MD_REVIEW_EMPTY_FRAGMENT in md
    assert _MD_NOTE_FRAGMENT in md
    assert _MD_DISCLAIMER_FRAGMENT in md


def test_markdown_conflict_warning_fragment():
    md = render_markdown(doc_conflict())
    assert _MD_CONFLICT_WARNING_FRAGMENT in md


def test_markdown_section_order():
    md = render_markdown(doc_conflict())
    positions = [md.index(heading) for heading in _MD_SECTION_ORDER]
    assert positions == sorted(positions)


def test_html_golden_fragments():
    html = render_html(doc_complete())
    assert _HTML_HEADLINE_FRAGMENT in html
    assert _HTML_VIEWPORT_FRAGMENT in html
    for head in _HTML_SECTION_HEADS:
        assert head in html
    assert "报告生成不等于测试通过" in html
    assert "tablewrap" in html


def test_html_section_order():
    html = render_html(doc_conflict())
    positions = [html.index(head) for head in _HTML_SECTION_HEADS]
    assert positions == sorted(positions)


def test_html_headlines_derive_from_dimensions():
    assert '<span class="badge warn">部分证据 — 非完整通过</span>' in render_html(doc_partial())
    assert _HTML_PARTIAL_HEADLINE_FRAGMENT in render_html(doc_unknown_safety())
    assert _HTML_PARTIAL_HEADLINE_FRAGMENT in render_html(doc_legacy())
    assert _HTML_CONFLICT_HEADLINE_FRAGMENT in render_html(doc_conflict())


def test_headline_never_claims_all_pass_when_partial():
    for doc_fn in (doc_partial, doc_conflict, doc_legacy, doc_unknown_safety):
        html = render_html(doc_fn())
        assert "全部通过" not in html
        assert '<span class="badge ok"' not in html


# --------------------------------------------------------------------------
# Injection / escaping
# --------------------------------------------------------------------------


def test_markdown_injection_neutered():
    md = render_markdown(doc_hostile())
    assert "<script" not in md
    assert "<img" not in md
    assert "&lt;script&gt;alert(1)&lt;/script&gt;" in md
    assert "SELECT a \\| b FROM t" in md
    assert "\\`x\\`" in md
    assert "r\\`ule\\|with\\nnewline" in md


def test_html_injection_neutered():
    html = render_html(doc_hostile())
    assert "<script" not in html
    assert "<img" not in html
    assert "&lt;script&gt;alert(1)&lt;/script&gt;" in html
    assert "&lt;img src=x onerror=alert(2)&gt;" in html
    assert "onerror=alert(2)</" not in html


def test_no_javascript_href_anywhere():
    html = render_html(doc_hostile())
    for line in html.splitlines():
        if 'href="' in line:
            rest = line.split('href="', 1)[1]
            assert not rest.lower().startswith(("javascript", "data:", "file:"))
    assert "javascript:" not in html


def test_issue_url_must_be_https():
    with pytest.raises(ContractError):
        FindingReview(
            review_id="rev-bad",
            reviewer="eve",
            reviewed_at="2026-09-06T15:00:00Z",
            evidence_digest=DELIVERY_ID,
            occurrence_ids=(CASE_A,),
            decision=ReviewDecision.NEEDS_MORE_EVIDENCE,
            reason="尝试注入",
            issue_url="javascript:alert(1)",
        )


def test_renderer_only_links_package_paths():
    html = render_html(doc_conflict())
    for line in html.splitlines():
        if 'href="' in line:
            target = line.split('href="', 1)[1].split('"', 1)[0]
            assert target.startswith("raw/") or target.startswith("assessment")
    # issue_url stays plain text, never an anchor (design 6.4.5).
    assert 'href="https' not in html
    assert "https://example.com/issue/1" in render_markdown(doc_conflict())


def test_renderer_refuses_scheme_bearing_file_path():
    from mtsql_typecheck.reporting.model import ReviewSet

    assessment = _assessment(_dims())
    bad_files = (
        EvidenceFile(
            path="javascript:alert(1)",
            role=FileRole.ASSESSMENT,
            size_bytes=1,
            sha256=HASH_1,
        ),
    )
    doc = _build(assessment, files=bad_files)
    with pytest.raises(UnsafeLinkError):
        render_markdown(doc)
    with pytest.raises(UnsafeLinkError):
        render_html(doc)


def test_special_filename_is_url_encoded():
    html = render_html(doc_longtext())
    assert "%E4%B8%AD%E6%96%87" in html  # 中文
    assert "%20" in html  # space
    md = render_markdown(doc_longtext())
    assert "%E4%B8%AD%E6%96%87" in md


# --------------------------------------------------------------------------
# Display budgets (design 6.5)
# --------------------------------------------------------------------------


def test_diff_summary_truncation_marker():
    doc = doc_longtext()
    detail = doc.case_details[0]
    assert "展示截断" in detail.diff_summary
    assert detail.diff_summary.endswith("……（展示截断：超过 100 行 / 1KiB 显示上限）")
    lines = detail.diff_summary.count("\n") + 1
    assert lines <= 101  # kept lines + at most one marker line
    assert len(detail.diff_summary.encode("utf-8")) <= 1024
    assert "行 0" in detail.diff_summary  # beginning is preserved, never silent
    md = render_markdown(doc)
    assert "展示截断" in md
    html = render_html(doc)
    assert "展示截断" in html


def test_diff_summary_line_cap_only():
    # 150 short lines hit the 100-line cap before the byte cap.
    text = "\n".join(f"line-{i}" for i in range(150))
    bounded = bound_diff_summary(text)
    assert bounded.count("\n") + 1 == 101
    assert bounded.endswith("……（展示截断：超过 100 行 / 1KiB 显示上限）")
    assert "line-0" in bounded and "line-149" not in bounded


def test_diff_summary_within_caps_unchanged():
    assert bound_diff_summary(None) is None
    assert bound_diff_summary("A: 2 行\nB: 3 行") == "A: 2 行\nB: 3 行"
    # Idempotent: re-bounding an already bounded summary adds no second marker.
    once = bound_diff_summary("x" * 2000)
    assert bound_diff_summary(once) == once


def test_render_size_limit():
    with pytest.raises(LimitExceeded):
        render_markdown(doc_complete(), max_bytes=100)
    with pytest.raises(LimitExceeded):
        render_html(doc_complete(), max_bytes=100)


def test_default_budget_is_8mib():
    from mtsql_typecheck.reporting.markdown import DEFAULT_MAX_MARKDOWN_BYTES
    from mtsql_typecheck.reporting.html import DEFAULT_MAX_HTML_BYTES

    assert DEFAULT_MAX_MARKDOWN_BYTES == 8 * 1024 * 1024
    assert DEFAULT_MAX_HTML_BYTES == 8 * 1024 * 1024


# --------------------------------------------------------------------------
# Candidate ordering (design 6.4.5 item 3)
# --------------------------------------------------------------------------


def test_occurrence_risk_ordering():
    assessment = _assessment(
        _dims(semantic=SemanticStatus.CONFLICT, semantic_kwargs=dict(checked=3)),
        native_kind=NativeKind.RUN,
        attempts=(
            AttemptSemanticResult(
                source_id=SOURCE_ID,
                attempt_id=ATTEMPT_1,
                case_id=CASE_A,
                original_comparison_hash=HASH_2,
                static_check_status="PASS",
                recompute=SemanticStatus.CONFLICT,
                recomputed_comparison_hash=HASH_1,
                exact_signature=HASH_1,
                fingerprint=FINGERPRINT,
                synthetic=SyntheticKind.REAL,
                reason_codes=(),
                limit_reasons=(),
            ),
            AttemptSemanticResult(
                source_id=SOURCE_ID,
                attempt_id=ATTEMPT_2,
                case_id=CASE_B,
                original_comparison_hash=HASH_2,
                static_check_status="PASS",
                recompute=SemanticStatus.RECOMPUTED,
                recomputed_comparison_hash=HASH_1,
                exact_signature=HASH_1,
                fingerprint=FINGERPRINT,
                synthetic=SyntheticKind.REAL,
                reason_codes=(),
                limit_reasons=(),
            ),
        ),
    )
    conflict = _occurrence(CASE_A, ATTEMPT_1, SemanticStatus.CONFLICT)
    real = _occurrence(CASE_B, ATTEMPT_2, SemanticStatus.RECOMPUTED)
    unknown = _occurrence(CASE_C, ATTEMPT_2, SemanticStatus.RECOMPUTED, synthetic=SyntheticKind.UNKNOWN)
    doc = _build(
        assessment,
        occurrences=(real, unknown, conflict),  # deliberately run-random order
        findings=FindingsSummary(
            real_candidates=1,
            synthetic_candidates=0,
            unknown_synthetic_candidates=1,
            conflicts=1,
            unique_case_ids=3,
            distinct_signatures=1,
            distinct_fingerprints=1,
            reviewed_confirmed=0,
        ),
    )
    assert [o.occurrence_id for o in doc.occurrences] == [
        conflict.occurrence_id,
        unknown.occurrence_id,
        real.occurrence_id,
    ]


def test_occurrence_must_belong_to_assessed_source():
    assessment = _assessment(_dims())
    stray = FindingOccurrence(
        source_id=OTHER_SOURCE_ID,
        attempt_id=ATTEMPT_1,
        case_id=CASE_A,
        recompute_status=SemanticStatus.NOT_RECOMPUTED,
    )
    with pytest.raises(ValueError, match="assessed source"):
        _build(assessment, occurrences=(stray,))


def test_case_detail_bindings_validated():
    from mtsql_typecheck.reporting.model import ReviewSet

    assessment = _assessment(_dims())
    occurrence = _occurrence(CASE_A, ATTEMPT_1, SemanticStatus.NOT_RECOMPUTED)
    detail = CaseDetailInput(
        occurrence_id=occurrence.occurrence_id,
        case_id=CASE_A,
        rule_id="r",
        rule_version=1,
        type_pair="int8~int8",
        review_ids=("rev-unknown",),
    )
    with pytest.raises(ValueError, match="unknown review"):
        _build(assessment, occurrences=(occurrence,), case_details=(detail,))
    stray_detail = CaseDetailInput(
        occurrence_id=CASE_B,  # not an occurrence id
        case_id=CASE_A,
        rule_id="r",
        rule_version=1,
        type_pair="int8~int8",
    )
    with pytest.raises(ValueError, match="unknown occurrence"):
        _build(assessment, case_details=(stray_detail,))


# --------------------------------------------------------------------------
# Codec round-trip and strictness
# --------------------------------------------------------------------------


@pytest.mark.parametrize("doc_fn", ALL_DOCS, ids=lambda fn: fn.__name__)
def test_decode_round_trip(doc_fn):
    doc = doc_fn()
    obj = doc.to_obj()
    decoded = decode_report_document(parse_strict_json(canonical_json(obj)))
    assert canonical_json(decoded.to_obj()) == canonical_json(obj)


def test_decode_rejects_unknown_fields():
    obj = doc_complete().to_obj()
    obj["unexpected"] = True
    with pytest.raises(ContractError):
        decode_report_document(obj)


def test_decode_rejects_wrong_schema_version():
    obj = doc_complete().to_obj()
    obj["schema_version"] = 2
    with pytest.raises(ContractError):
        decode_report_document(obj)


def test_decode_rejects_bad_delivery_id():
    obj = doc_complete().to_obj()
    obj["header"]["delivery_id"] = "not-a-hash"
    with pytest.raises(ContractError):
        decode_report_document(obj)


def test_decode_rejects_bad_case_detail_hash():
    obj = doc_longtext().to_obj()
    obj["findings"]["case_details"][0]["occurrence_id"] = "zz"
    with pytest.raises(ContractError):
        decode_report_document(obj)


# --------------------------------------------------------------------------
# Renderer agreement (both formats render the same typed model)
# --------------------------------------------------------------------------


@pytest.mark.parametrize("doc_fn", ALL_DOCS, ids=lambda fn: fn.__name__)
def test_markdown_and_html_agree(doc_fn):
    doc = doc_fn()
    md = render_markdown(doc)
    html = render_html(doc)
    for occurrence in doc.occurrences:
        assert occurrence.occurrence_id in md
        assert occurrence.occurrence_id in html
    for dimension in (
        doc.header.structural,
        doc.header.semantic,
        doc.header.provenance,
        doc.header.execution_safety,
    ):
        assert dimension.status.value in md
        assert dimension.status.value in html
    for name, value in (
        ("真实候选", doc.findings.real_candidates),
        ("合成未知候选", doc.findings.unknown_synthetic_candidates),
        ("语义冲突", doc.findings.conflicts),
    ):
        assert name in md and name in html
        assert str(value) in md and str(value) in html


def test_renderers_are_pure_and_deterministic():
    doc = doc_conflict()
    assert render_markdown(doc) == render_markdown(doc)
    assert render_html(doc) == render_html(doc)
